# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 17:25
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    Car = apps.get_model("main", "Car")
    car1 = Car(id=1, name='BMW', img='license-plate5.jpg', year=2001, nmb='KZ008BMW01', owner='Duman')
    car1.save()

    Shtraf = apps.get_model("main", "Shtraf")
    Shtraf(id=1, sum=10000, pay_before='2015-01-01', status=1, car=car1).save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20170506_2325'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
